// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request for CheckCompatibility.
public struct CheckCompatibilityRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the resource to check compatibility for. The format
  /// is either of following:
  /// * projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/compatibility/subjects/*/versions: Check compatibility with one or
  ///   more versions of the specified subject.
  /// * projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/compatibility/subjects/{subject}/versions/{version}: Check
  ///   compatibility with a specific version of the subject.
  public var name: Swift.String = Swift.String()

  /// Optional. The schema type of the schema.
  public var schemaType: Schema.SchemaType? = nil

  /// Required. The schema payload
  public var schema: Swift.String = Swift.String()

  /// Optional. The schema references used by the schema.
  public var references: [Schema.SchemaReference] = []

  /// Optional. If true, the response will contain the compatibility check result
  /// with reasons for failed checks. The default is false.
  public var verbose: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CheckCompatibilityRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CheckCompatibilityRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let schemaType = CodingKeys(stringValue: "schemaType")
    static let schema = CodingKeys(stringValue: "schema")
    static let references = CodingKeys(stringValue: "references")
    static let verbose = CodingKeys(stringValue: "verbose")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "schemaType",
      "schema",
      "references",
      "verbose",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.schemaType = try container.decodeIfPresent(Schema.SchemaType.self, forKey: .schemaType)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .schema) {
      self.schema = value
    }
    if let value = try container.decodeIfPresent([Schema.SchemaReference].self, forKey: .references)
    {
      self.references = value
    }
    self.verbose = try container.decodeIfPresent(Swift.Bool.self, forKey: .verbose)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.schemaType, forKey: .schemaType)
    try container.encode(self.schema, forKey: .schema)
    try container.encode(self.references, forKey: .references)
    try container.encodeIfPresent(self.verbose, forKey: .verbose)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.CheckCompatibilityRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
