// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Context represents an independent schema grouping in a schema registry
/// instance.
public struct Context: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the context. Structured like:
  /// `projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/contexts/{context}`
  /// The context name {context} can contain the following:
  /// * Up to 255 characters.
  /// * Allowed characters: letters (uppercase or lowercase), numbers, and the
  /// following special characters: `.`, `-`, `_`, `+`, `%`, and `~`.
  public var name: Swift.String = Swift.String()

  /// Optional. The subjects of the context.
  public var subjects: [Swift.String] = []

  /// Initialize a new instance of `Context`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Context().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.Context"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
