// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for CreateVersion.
public struct CreateVersionRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The subject to create the version for. Structured like:
  /// `projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/subjects/{subject}`
  /// or
  /// `projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/contexts/{context}/subjects/{subject}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The version to create. It is optional. If not specified, the
  /// version will be created with the max version ID of the subject increased
  /// by 1. If the version ID is specified, it will be used as the new version ID
  /// and must not be used by an existing version of the subject.
  public var version: Swift.Int32? = nil

  /// Optional. The schema ID of the schema. If not specified, the schema ID will
  /// be generated by the server. If the schema ID is specified, it must not be
  /// used by an existing schema that is different from the schema to be created.
  public var id: Swift.Int32? = nil

  /// Optional. The type of the schema. It is optional. If not specified, the
  /// schema type will be AVRO.
  public var schemaType: Schema.SchemaType? = nil

  /// Required. The schema payload
  public var schema: Swift.String = Swift.String()

  /// Optional. The schema references used by the schema.
  public var references: [Schema.SchemaReference] = []

  /// Optional. If true, the schema will be normalized before being stored. The
  /// default is false.
  public var normalize: Swift.Bool? = nil

  /// Initialize a new instance of `CreateVersionRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateVersionRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.CreateVersionRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
