// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request to create a schema registry instance.
public struct CreateSchemaRegistryRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The parent whose schema registry instance is to be created.
  /// Structured like: `projects/{project}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. The schema registry instance ID to use for this schema registry.
  /// The ID must contain only letters (a-z, A-Z), numbers (0-9), and underscores
  /// (-). The maximum length is 63 characters.
  /// The ID must not start with a number.
  public var schemaRegistryId: Swift.String = Swift.String()

  /// Required. The schema registry instance to create.
  /// The name field is ignored.
  public var schemaRegistry: SchemaRegistry? = nil

  /// Initialize a new instance of `CreateSchemaRegistryRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateSchemaRegistryRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.CreateSchemaRegistryRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
