// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for CreateVersion.
public struct CreateVersionRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The subject to create the version for. Structured like:
  /// `projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/subjects/{subject}`
  /// or
  /// `projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/contexts/{context}/subjects/{subject}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The version to create. It is optional. If not specified, the
  /// version will be created with the max version ID of the subject increased
  /// by 1. If the version ID is specified, it will be used as the new version ID
  /// and must not be used by an existing version of the subject.
  public var version: Swift.Int32? = nil

  /// Optional. The schema ID of the schema. If not specified, the schema ID will
  /// be generated by the server. If the schema ID is specified, it must not be
  /// used by an existing schema that is different from the schema to be created.
  public var id: Swift.Int32? = nil

  /// Optional. The type of the schema. It is optional. If not specified, the
  /// schema type will be AVRO.
  public var schemaType: Schema.SchemaType? = nil

  /// Required. The schema payload
  public var schema: Swift.String = Swift.String()

  /// Optional. The schema references used by the schema.
  public var references: [Schema.SchemaReference] = []

  /// Optional. If true, the schema will be normalized before being stored. The
  /// default is false.
  public var normalize: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateVersionRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateVersionRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let version = CodingKeys(stringValue: "version")
    static let id = CodingKeys(stringValue: "id")
    static let schemaType = CodingKeys(stringValue: "schemaType")
    static let schema = CodingKeys(stringValue: "schema")
    static let references = CodingKeys(stringValue: "references")
    static let normalize = CodingKeys(stringValue: "normalize")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "version",
      "id",
      "schemaType",
      "schema",
      "references",
      "normalize",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.version = try container.decodeIfPresent(Swift.Int32.self, forKey: .version)
    self.id = try container.decodeIfPresent(Swift.Int32.self, forKey: .id)
    self.schemaType = try container.decodeIfPresent(Schema.SchemaType.self, forKey: .schemaType)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .schema) {
      self.schema = value
    }
    if let value = try container.decodeIfPresent([Schema.SchemaReference].self, forKey: .references)
    {
      self.references = value
    }
    self.normalize = try container.decodeIfPresent(Swift.Bool.self, forKey: .normalize)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.version, forKey: .version)
    try container.encodeIfPresent(self.id, forKey: .id)
    try container.encodeIfPresent(self.schemaType, forKey: .schemaType)
    try container.encode(self.schema, forKey: .schema)
    try container.encode(self.references, forKey: .references)
    try container.encodeIfPresent(self.normalize, forKey: .normalize)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.CreateVersionRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
