// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request for DeleteVersion.
public struct DeleteVersionRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the subject version to delete. Structured like:
  /// `projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/subjects/{subject}/versions/{version}`
  /// or
  /// `projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/contexts/{context}/subjects/{subject}/versions/{version}`
  public var name: Swift.String = Swift.String()

  /// Optional. If true, both the version and the referenced schema ID will be
  /// permanently deleted. The default is false. If false, the version will be
  /// deleted but the schema ID will be retained. Soft-deleted versions can still
  /// be searched in ListVersions API call with deleted=true query parameter. A
  /// soft-delete of a version must be performed before a hard-delete.
  public var permanent: Swift.Bool? = nil

  /// Initialize a new instance of `DeleteVersionRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteVersionRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.DeleteVersionRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
