// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for LookupVersion.
public struct LookupVersionRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The subject to lookup the schema in. Structured like:
  /// `projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/subjects/{subject}`
  /// or
  /// `projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/contexts/{context}/subjects/{subject}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The schema type of the schema.
  public var schemaType: Schema.SchemaType? = nil

  /// Required. The schema payload
  public var schema: Swift.String = Swift.String()

  /// Optional. The schema references used by the schema.
  public var references: [Schema.SchemaReference] = []

  /// Optional. If true, the schema will be normalized before being looked up.
  /// The default is false.
  public var normalize: Swift.Bool? = nil

  /// Optional. If true, soft-deleted versions will be included in lookup, no
  /// matter if the subject is active or soft-deleted. If false, soft-deleted
  /// versions will be excluded. The default is false.
  public var deleted: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LookupVersionRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LookupVersionRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let schemaType = CodingKeys(stringValue: "schemaType")
    static let schema = CodingKeys(stringValue: "schema")
    static let references = CodingKeys(stringValue: "references")
    static let normalize = CodingKeys(stringValue: "normalize")
    static let deleted = CodingKeys(stringValue: "deleted")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "schemaType",
      "schema",
      "references",
      "normalize",
      "deleted",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.schemaType = try container.decodeIfPresent(Schema.SchemaType.self, forKey: .schemaType)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .schema) {
      self.schema = value
    }
    if let value = try container.decodeIfPresent([Schema.SchemaReference].self, forKey: .references)
    {
      self.references = value
    }
    self.normalize = try container.decodeIfPresent(Swift.Bool.self, forKey: .normalize)
    self.deleted = try container.decodeIfPresent(Swift.Bool.self, forKey: .deleted)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.schemaType, forKey: .schemaType)
    try container.encode(self.schema, forKey: .schema)
    try container.encode(self.references, forKey: .references)
    try container.encodeIfPresent(self.normalize, forKey: .normalize)
    try container.encodeIfPresent(self.deleted, forKey: .deleted)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.LookupVersionRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
