// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for LookupVersion.
public struct LookupVersionRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The subject to lookup the schema in. Structured like:
  /// `projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/subjects/{subject}`
  /// or
  /// `projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/contexts/{context}/subjects/{subject}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The schema type of the schema.
  public var schemaType: Schema.SchemaType? = nil

  /// Required. The schema payload
  public var schema: Swift.String = Swift.String()

  /// Optional. The schema references used by the schema.
  public var references: [Schema.SchemaReference] = []

  /// Optional. If true, the schema will be normalized before being looked up.
  /// The default is false.
  public var normalize: Swift.Bool? = nil

  /// Optional. If true, soft-deleted versions will be included in lookup, no
  /// matter if the subject is active or soft-deleted. If false, soft-deleted
  /// versions will be excluded. The default is false.
  public var deleted: Swift.Bool? = nil

  /// Initialize a new instance of `LookupVersionRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LookupVersionRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.LookupVersionRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
