// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleCloudGax

/// SchemaRegistry is a service that allows users to manage schemas for their
/// Kafka clusters. It provides APIs to register, list, and delete schemas, as
/// well as to get the schema for a given schema id or a given version id under a
/// subject, to update the global or subject-specific compatibility mode, and to
/// check the compatibility of a schema against a subject or a version. The main
/// resource hierarchy is as follows:
///
/// * SchemaRegistry
/// * SchemaRegistry/Context
/// * SchemaRegistry/Context/Schema
/// * SchemaRegistry/Context/Subject
/// * SchemaRegistry/Context/Subject/Version
/// * SchemaRegistry/Config
/// * SchemaRegistry/Mode
///
/// **SchemaRegistry** is the root resource to represent a schema registry
/// instance. A customer can have multiple schema registry instances in a
/// project.
///
/// **Context** is a context resource that represents a group of
/// schemas, subjects and versions. A schema registry instance can have multiple
/// contexts and always has a 'default' context. Contexts are independent of each
/// other. Context is optional and if not specified, it falls back to the
/// 'default' context.
///
/// **Schema** is a schema resource that represents a unique schema in a context
/// of a schema registry instance. Each schema has a unique schema id, and can be
/// referenced by a version of a subject.
///
/// **Subject** refers to the name under which the schema is registered. A
/// typical subject is the Kafka topic name. A schema registry instance can have
/// multiple subjects.
///
/// **Version** represents a version of a subject. A subject can have multiple
/// versions. Creation of new version of a subject is guarded by the
/// compatibility mode configured globally or for the subject specifically.
///
/// **Config** represents a config at global level cross all registry
/// instances or at subject level. Currently, only compatibility is supported in
/// config.
///
/// **Mode** represents the mode of a schema registry or a specific subject.
/// Three modes are supported:
/// * READONLY: The schema registry is in read-only mode, no write operations
/// allowed..
/// * READWRITE: The schema registry is in read-write mode, which allows limited
/// write operations on the schema.
/// * IMPORT: The schema registry is in import mode, which allows more editing
/// operations on the schema for data importing purposes.
///
/// @Snippet(path: "ManagedSchemaRegistryQuickstart")
public final class ManagedSchemaRegistryClient: Clients.ManagedSchemaRegistryProtocol, Sendable {
  let inner: any Clients.ManagedSchemaRegistryStub

  /// Creates a new `ManagedSchemaRegistryClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ManagedSchemaRegistryStub = try Clients.ManagedSchemaRegistryTransport(
      options)
    inner = Clients.ManagedSchemaRegistryRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ManagedSchemaRegistryLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Get the schema registry instance.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_GetSchemaRegistry")
  public func getSchemaRegistry(
    request: GetSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry {
    try await self.inner.getSchemaRegistry(request: request, options: options)
  }

  /// List schema registries.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListSchemaRegistries")
  public func listSchemaRegistries(
    request: ListSchemaRegistriesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse {
    try await self.inner.listSchemaRegistries(request: request, options: options)
  }

  /// Create a schema registry instance.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_CreateSchemaRegistry")
  public func createSchemaRegistry(
    request: CreateSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry {
    try await self.inner.createSchemaRegistry(request: request, options: options)
  }

  /// Delete a schema registry instance.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_DeleteSchemaRegistry")
  public func deleteSchemaRegistry(
    request: DeleteSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteSchemaRegistry(request: request, options: options)
  }

  /// Get the context.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_GetContext")
  public func getContext(
    request: GetContextRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Context {
    try await self.inner.getContext(request: request, options: options)
  }

  /// List contexts for a schema registry.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListContexts")
  public func listContexts(
    request: ListContextsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.listContexts(request: request, options: options)
  }

  /// Get the schema for the given schema id.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_GetSchema")
  public func getSchema(
    request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema {
    try await self.inner.getSchema(request: request, options: options)
  }

  /// Get the schema string for the given schema id.
  /// The response will be the schema string.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_GetRawSchema")
  public func getRawSchema(
    request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.getRawSchema(request: request, options: options)
  }

  /// List the schema versions for the given schema id.
  /// The response will be an array of subject-version pairs as:
  /// [{"subject":"subject1", "version":1}, {"subject":"subject2", "version":2}].
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListSchemaVersions")
  public func listSchemaVersions(
    request: ListSchemaVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.listSchemaVersions(request: request, options: options)
  }

  /// List the supported schema types.
  /// The response will be an array of schema types.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListSchemaTypes")
  public func listSchemaTypes(
    request: ListSchemaTypesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.listSchemaTypes(request: request, options: options)
  }

  /// List subjects in the schema registry.
  /// The response will be an array of subject names.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListSubjects")
  public func listSubjects(
    request: ListSubjectsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.listSubjects(request: request, options: options)
  }

  /// List subjects which reference a particular schema id.
  /// The response will be an array of subject names.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListSubjectsBySchemaId")
  public func listSubjectsBySchemaId(
    request: ListSubjectsBySchemaIdRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.listSubjectsBySchemaId(request: request, options: options)
  }

  /// Delete a subject.
  /// The response will be an array of versions of the deleted subject.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_DeleteSubject")
  public func deleteSubject(
    request: DeleteSubjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.deleteSubject(request: request, options: options)
  }

  /// Lookup a schema under the specified subject.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_LookupVersion")
  public func lookupVersion(
    request: LookupVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion {
    try await self.inner.lookupVersion(request: request, options: options)
  }

  /// Get a versioned schema (schema with subject/version) of a subject.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_GetVersion")
  public func getVersion(
    request: GetVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion {
    try await self.inner.getVersion(request: request, options: options)
  }

  /// Get the schema string only for a version of a subject.
  /// The response will be the schema string.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_GetRawSchemaVersion")
  public func getRawSchemaVersion(
    request: GetVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.getRawSchemaVersion(request: request, options: options)
  }

  /// Get all versions of a subject.
  /// The response will be an array of versions of the subject.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListVersions")
  public func listVersions(
    request: ListVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.listVersions(request: request, options: options)
  }

  /// Register a new version under a given subject with the given schema.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_CreateVersion")
  public func createVersion(
    request: CreateVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse {
    try await self.inner.createVersion(request: request, options: options)
  }

  /// Delete a version of a subject.
  /// The response will be the deleted version id.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_DeleteVersion")
  public func deleteVersion(
    request: DeleteVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.deleteVersion(request: request, options: options)
  }

  /// Get a list of IDs of schemas that reference the schema with the given
  /// subject and version.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListReferencedSchemas")
  public func listReferencedSchemas(
    request: ListReferencedSchemasRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    try await self.inner.listReferencedSchemas(request: request, options: options)
  }

  /// Check compatibility of a schema with all versions or a specific version of
  /// a subject.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_CheckCompatibility")
  public func checkCompatibility(
    request: CheckCompatibilityRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse {
    try await self.inner.checkCompatibility(request: request, options: options)
  }

  /// Get schema config at global level or for a subject.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_GetSchemaConfig")
  public func getSchemaConfig(
    request: GetSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
    try await self.inner.getSchemaConfig(request: request, options: options)
  }

  /// Update config at global level or for a subject.
  /// Creates a SchemaSubject-level SchemaConfig if it does not exist.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_UpdateSchemaConfig")
  public func updateSchemaConfig(
    request: UpdateSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
    try await self.inner.updateSchemaConfig(request: request, options: options)
  }

  /// Delete schema config for a subject.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_DeleteSchemaConfig")
  public func deleteSchemaConfig(
    request: DeleteSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
    try await self.inner.deleteSchemaConfig(request: request, options: options)
  }

  /// Get mode at global level or for a subject.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_GetSchemaMode")
  public func getSchemaMode(
    request: GetSchemaModeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
    try await self.inner.getSchemaMode(request: request, options: options)
  }

  /// Update mode at global level or for a subject.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_UpdateSchemaMode")
  public func updateSchemaMode(
    request: UpdateSchemaModeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
    try await self.inner.updateSchemaMode(request: request, options: options)
  }

  /// Delete schema mode for a subject.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_DeleteSchemaMode")
  public func deleteSchemaMode(
    request: DeleteSchemaModeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
    try await self.inner.deleteSchemaMode(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedSchemaRegistry_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ManagedSchemaRegistryClient`.
  ///
  /// To mock `ManagedSchemaRegistryClient` change your functions to receive
  /// `some ManagedSchemaRegistryProtocol` or `any ManagedSchemaRegistryProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ManagedSchemaRegistryProtocol {
    /// See `ManagedSchemaRegistryClient.getSchemaRegistry`.
    func getSchemaRegistry(request: GetSchemaRegistryRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry

    /// See `ManagedSchemaRegistryClient.getSchemaRegistry`.
    func getSchemaRegistry(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry

    /// See `ManagedSchemaRegistryClient.listSchemaRegistries`.
    func listSchemaRegistries(request: ListSchemaRegistriesRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse

    /// See `ManagedSchemaRegistryClient.listSchemaRegistries`.
    func listSchemaRegistries(
      parent: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse

    /// See `ManagedSchemaRegistryClient.createSchemaRegistry`.
    func createSchemaRegistry(request: CreateSchemaRegistryRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry

    /// See `ManagedSchemaRegistryClient.createSchemaRegistry`.
    func createSchemaRegistry(
      parent: Swift.String,
      schemaRegistry: SchemaRegistry?,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry

    /// See `ManagedSchemaRegistryClient.deleteSchemaRegistry`.
    func deleteSchemaRegistry(request: DeleteSchemaRegistryRequest) async throws

    /// See `ManagedSchemaRegistryClient.deleteSchemaRegistry`.
    func deleteSchemaRegistry(
      name: Swift.String,
    ) async throws

    /// See `ManagedSchemaRegistryClient.getContext`.
    func getContext(request: GetContextRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.Context

    /// See `ManagedSchemaRegistryClient.getContext`.
    func getContext(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Context

    /// See `ManagedSchemaRegistryClient.listContexts`.
    func listContexts(request: ListContextsRequest) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listContexts`.
    func listContexts(
      parent: Swift.String,
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.getSchema`.
    func getSchema(request: GetSchemaRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema

    /// See `ManagedSchemaRegistryClient.getSchema`.
    func getSchema(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema

    /// See `ManagedSchemaRegistryClient.getRawSchema`.
    func getRawSchema(request: GetSchemaRequest) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.getRawSchema`.
    func getRawSchema(
      name: Swift.String,
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSchemaVersions`.
    func listSchemaVersions(request: ListSchemaVersionsRequest) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSchemaVersions`.
    func listSchemaVersions(
      parent: Swift.String,
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSchemaTypes`.
    func listSchemaTypes(request: ListSchemaTypesRequest) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSchemaTypes`.
    func listSchemaTypes(
      parent: Swift.String,
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSubjects`.
    func listSubjects(request: ListSubjectsRequest) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSubjects`.
    func listSubjects(
      parent: Swift.String,
      subjectPrefix: Swift.String?,
      deleted: Swift.Bool?,
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSubjectsBySchemaId`.
    func listSubjectsBySchemaId(request: ListSubjectsBySchemaIdRequest) async throws
      -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSubjectsBySchemaId`.
    func listSubjectsBySchemaId(
      parent: Swift.String,
      subject: Swift.String?,
      deleted: Swift.Bool?,
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.deleteSubject`.
    func deleteSubject(request: DeleteSubjectRequest) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.deleteSubject`.
    func deleteSubject(
      name: Swift.String,
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.lookupVersion`.
    func lookupVersion(request: LookupVersionRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion

    /// See `ManagedSchemaRegistryClient.lookupVersion`.
    func lookupVersion(
      parent: Swift.String,
      schema: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion

    /// See `ManagedSchemaRegistryClient.getVersion`.
    func getVersion(request: GetVersionRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion

    /// See `ManagedSchemaRegistryClient.getVersion`.
    func getVersion(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion

    /// See `ManagedSchemaRegistryClient.getRawSchemaVersion`.
    func getRawSchemaVersion(request: GetVersionRequest) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.getRawSchemaVersion`.
    func getRawSchemaVersion(
      name: Swift.String,
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listVersions`.
    func listVersions(request: ListVersionsRequest) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listVersions`.
    func listVersions(
      parent: Swift.String,
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.createVersion`.
    func createVersion(request: CreateVersionRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse

    /// See `ManagedSchemaRegistryClient.createVersion`.
    func createVersion(
      parent: Swift.String,
      version: Swift.Int32?,
      id: Swift.Int32?,
      schemaType: Schema.SchemaType?,
      schema: Swift.String,
      references: [Schema.SchemaReference],
      normalize: Swift.Bool?,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse

    /// See `ManagedSchemaRegistryClient.deleteVersion`.
    func deleteVersion(request: DeleteVersionRequest) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.deleteVersion`.
    func deleteVersion(
      name: Swift.String,
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listReferencedSchemas`.
    func listReferencedSchemas(request: ListReferencedSchemasRequest) async throws
      -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listReferencedSchemas`.
    func listReferencedSchemas(
      parent: Swift.String,
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.checkCompatibility`.
    func checkCompatibility(request: CheckCompatibilityRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse

    /// See `ManagedSchemaRegistryClient.checkCompatibility`.
    func checkCompatibility(
      name: Swift.String,
      schema: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse

    /// See `ManagedSchemaRegistryClient.getSchemaConfig`.
    func getSchemaConfig(request: GetSchemaConfigRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    /// See `ManagedSchemaRegistryClient.getSchemaConfig`.
    func getSchemaConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    /// See `ManagedSchemaRegistryClient.updateSchemaConfig`.
    func updateSchemaConfig(request: UpdateSchemaConfigRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    /// See `ManagedSchemaRegistryClient.updateSchemaConfig`.
    func updateSchemaConfig(
      name: Swift.String,
      compatibility: SchemaConfig.CompatibilityType?,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    /// See `ManagedSchemaRegistryClient.deleteSchemaConfig`.
    func deleteSchemaConfig(request: DeleteSchemaConfigRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    /// See `ManagedSchemaRegistryClient.deleteSchemaConfig`.
    func deleteSchemaConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    /// See `ManagedSchemaRegistryClient.getSchemaMode`.
    func getSchemaMode(request: GetSchemaModeRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    /// See `ManagedSchemaRegistryClient.getSchemaMode`.
    func getSchemaMode(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    /// See `ManagedSchemaRegistryClient.updateSchemaMode`.
    func updateSchemaMode(request: UpdateSchemaModeRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    /// See `ManagedSchemaRegistryClient.updateSchemaMode`.
    func updateSchemaMode(
      name: Swift.String,
      mode: SchemaMode.ModeType,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    /// See `ManagedSchemaRegistryClient.deleteSchemaMode`.
    func deleteSchemaMode(request: DeleteSchemaModeRequest) async throws
      -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    /// See `ManagedSchemaRegistryClient.deleteSchemaMode`.
    func deleteSchemaMode(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    /// See `ManagedSchemaRegistryClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `ManagedSchemaRegistryClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ManagedSchemaRegistryClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `ManagedSchemaRegistryClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `ManagedSchemaRegistryClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ManagedSchemaRegistryClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ManagedSchemaRegistryClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `ManagedSchemaRegistryClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `ManagedSchemaRegistryClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `ManagedSchemaRegistryClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `ManagedSchemaRegistryClient.getSchemaRegistry`.
    func getSchemaRegistry(
      request: GetSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry

    /// See `ManagedSchemaRegistryClient.listSchemaRegistries`.
    func listSchemaRegistries(
      request: ListSchemaRegistriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse

    /// See `ManagedSchemaRegistryClient.createSchemaRegistry`.
    func createSchemaRegistry(
      request: CreateSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry

    /// See `ManagedSchemaRegistryClient.deleteSchemaRegistry`.
    func deleteSchemaRegistry(
      request: DeleteSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ManagedSchemaRegistryClient.getContext`.
    func getContext(
      request: GetContextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Context

    /// See `ManagedSchemaRegistryClient.listContexts`.
    func listContexts(
      request: ListContextsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.getSchema`.
    func getSchema(
      request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema

    /// See `ManagedSchemaRegistryClient.getRawSchema`.
    func getRawSchema(
      request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSchemaVersions`.
    func listSchemaVersions(
      request: ListSchemaVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSchemaTypes`.
    func listSchemaTypes(
      request: ListSchemaTypesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSubjects`.
    func listSubjects(
      request: ListSubjectsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listSubjectsBySchemaId`.
    func listSubjectsBySchemaId(
      request: ListSubjectsBySchemaIdRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.deleteSubject`.
    func deleteSubject(
      request: DeleteSubjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.lookupVersion`.
    func lookupVersion(
      request: LookupVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion

    /// See `ManagedSchemaRegistryClient.getVersion`.
    func getVersion(
      request: GetVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion

    /// See `ManagedSchemaRegistryClient.getRawSchemaVersion`.
    func getRawSchemaVersion(
      request: GetVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listVersions`.
    func listVersions(
      request: ListVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.createVersion`.
    func createVersion(
      request: CreateVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse

    /// See `ManagedSchemaRegistryClient.deleteVersion`.
    func deleteVersion(
      request: DeleteVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.listReferencedSchemas`.
    func listReferencedSchemas(
      request: ListReferencedSchemasRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    /// See `ManagedSchemaRegistryClient.checkCompatibility`.
    func checkCompatibility(
      request: CheckCompatibilityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse

    /// See `ManagedSchemaRegistryClient.getSchemaConfig`.
    func getSchemaConfig(
      request: GetSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    /// See `ManagedSchemaRegistryClient.updateSchemaConfig`.
    func updateSchemaConfig(
      request: UpdateSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    /// See `ManagedSchemaRegistryClient.deleteSchemaConfig`.
    func deleteSchemaConfig(
      request: DeleteSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    /// See `ManagedSchemaRegistryClient.getSchemaMode`.
    func getSchemaMode(
      request: GetSchemaModeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    /// See `ManagedSchemaRegistryClient.updateSchemaMode`.
    func updateSchemaMode(
      request: UpdateSchemaModeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    /// See `ManagedSchemaRegistryClient.deleteSchemaMode`.
    func deleteSchemaMode(
      request: DeleteSchemaModeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    /// See `ManagedSchemaRegistryClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ManagedSchemaRegistryClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ManagedSchemaRegistryClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `ManagedSchemaRegistryClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ManagedSchemaRegistryClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ManagedSchemaRegistryClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ManagedSchemaRegistryClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ManagedSchemaRegistryProtocol {
  public func getSchemaRegistry(request: GetSchemaRegistryRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry
  {
    try await self.getSchemaRegistry(request: request, options: .init())
  }

  public func getSchemaRegistry(
    request: GetSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSchemaRegistry(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry {
    let request = GetSchemaRegistryRequest().with {
      $0.name = name
    }
    return try await self.getSchemaRegistry(request: request)
  }

  public func listSchemaRegistries(request: ListSchemaRegistriesRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse
  {
    try await self.listSchemaRegistries(request: request, options: .init())
  }

  public func listSchemaRegistries(
    request: ListSchemaRegistriesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSchemaRegistries(
    parent: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse {
    let request = ListSchemaRegistriesRequest().with {
      $0.parent = parent
    }
    return try await self.listSchemaRegistries(request: request)
  }

  public func createSchemaRegistry(request: CreateSchemaRegistryRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry
  {
    try await self.createSchemaRegistry(request: request, options: .init())
  }

  public func createSchemaRegistry(
    request: CreateSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createSchemaRegistry(
    parent: Swift.String,
    schemaRegistry: SchemaRegistry?,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry {
    let request = CreateSchemaRegistryRequest().with {
      $0.parent = parent
      $0.schemaRegistry = schemaRegistry
    }
    return try await self.createSchemaRegistry(request: request)
  }

  public func deleteSchemaRegistry(request: DeleteSchemaRegistryRequest) async throws {
    try await self.deleteSchemaRegistry(request: request, options: .init())
  }

  public func deleteSchemaRegistry(
    request: DeleteSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSchemaRegistry(
    name: Swift.String,
  ) async throws {
    let request = DeleteSchemaRegistryRequest().with {
      $0.name = name
    }
    try await self.deleteSchemaRegistry(request: request)
  }

  public func getContext(request: GetContextRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.Context
  {
    try await self.getContext(request: request, options: .init())
  }

  public func getContext(
    request: GetContextRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Context {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getContext(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Context {
    let request = GetContextRequest().with {
      $0.name = name
    }
    return try await self.getContext(request: request)
  }

  public func listContexts(request: ListContextsRequest) async throws -> GoogleApi.HttpBody {
    try await self.listContexts(request: request, options: .init())
  }

  public func listContexts(
    request: ListContextsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listContexts(
    parent: Swift.String,
  ) async throws -> GoogleApi.HttpBody {
    let request = ListContextsRequest().with {
      $0.parent = parent
    }
    return try await self.listContexts(request: request)
  }

  public func getSchema(request: GetSchemaRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema
  {
    try await self.getSchema(request: request, options: .init())
  }

  public func getSchema(
    request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSchema(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema {
    let request = GetSchemaRequest().with {
      $0.name = name
    }
    return try await self.getSchema(request: request)
  }

  public func getRawSchema(request: GetSchemaRequest) async throws -> GoogleApi.HttpBody {
    try await self.getRawSchema(request: request, options: .init())
  }

  public func getRawSchema(
    request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getRawSchema(
    name: Swift.String,
  ) async throws -> GoogleApi.HttpBody {
    let request = GetSchemaRequest().with {
      $0.name = name
    }
    return try await self.getRawSchema(request: request)
  }

  public func listSchemaVersions(request: ListSchemaVersionsRequest) async throws
    -> GoogleApi.HttpBody
  {
    try await self.listSchemaVersions(request: request, options: .init())
  }

  public func listSchemaVersions(
    request: ListSchemaVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSchemaVersions(
    parent: Swift.String,
  ) async throws -> GoogleApi.HttpBody {
    let request = ListSchemaVersionsRequest().with {
      $0.parent = parent
    }
    return try await self.listSchemaVersions(request: request)
  }

  public func listSchemaTypes(request: ListSchemaTypesRequest) async throws -> GoogleApi.HttpBody {
    try await self.listSchemaTypes(request: request, options: .init())
  }

  public func listSchemaTypes(
    request: ListSchemaTypesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSchemaTypes(
    parent: Swift.String,
  ) async throws -> GoogleApi.HttpBody {
    let request = ListSchemaTypesRequest().with {
      $0.parent = parent
    }
    return try await self.listSchemaTypes(request: request)
  }

  public func listSubjects(request: ListSubjectsRequest) async throws -> GoogleApi.HttpBody {
    try await self.listSubjects(request: request, options: .init())
  }

  public func listSubjects(
    request: ListSubjectsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSubjects(
    parent: Swift.String,
    subjectPrefix: Swift.String?,
    deleted: Swift.Bool?,
  ) async throws -> GoogleApi.HttpBody {
    let request = ListSubjectsRequest().with {
      $0.parent = parent
      $0.subjectPrefix = subjectPrefix
      $0.deleted = deleted
    }
    return try await self.listSubjects(request: request)
  }

  public func listSubjectsBySchemaId(request: ListSubjectsBySchemaIdRequest) async throws
    -> GoogleApi.HttpBody
  {
    try await self.listSubjectsBySchemaId(request: request, options: .init())
  }

  public func listSubjectsBySchemaId(
    request: ListSubjectsBySchemaIdRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSubjectsBySchemaId(
    parent: Swift.String,
    subject: Swift.String?,
    deleted: Swift.Bool?,
  ) async throws -> GoogleApi.HttpBody {
    let request = ListSubjectsBySchemaIdRequest().with {
      $0.parent = parent
      $0.subject = subject
      $0.deleted = deleted
    }
    return try await self.listSubjectsBySchemaId(request: request)
  }

  public func deleteSubject(request: DeleteSubjectRequest) async throws -> GoogleApi.HttpBody {
    try await self.deleteSubject(request: request, options: .init())
  }

  public func deleteSubject(
    request: DeleteSubjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSubject(
    name: Swift.String,
  ) async throws -> GoogleApi.HttpBody {
    let request = DeleteSubjectRequest().with {
      $0.name = name
    }
    return try await self.deleteSubject(request: request)
  }

  public func lookupVersion(request: LookupVersionRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion
  {
    try await self.lookupVersion(request: request, options: .init())
  }

  public func lookupVersion(
    request: LookupVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func lookupVersion(
    parent: Swift.String,
    schema: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion {
    let request = LookupVersionRequest().with {
      $0.parent = parent
      $0.schema = schema
    }
    return try await self.lookupVersion(request: request)
  }

  public func getVersion(request: GetVersionRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion
  {
    try await self.getVersion(request: request, options: .init())
  }

  public func getVersion(
    request: GetVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getVersion(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion {
    let request = GetVersionRequest().with {
      $0.name = name
    }
    return try await self.getVersion(request: request)
  }

  public func getRawSchemaVersion(request: GetVersionRequest) async throws -> GoogleApi.HttpBody {
    try await self.getRawSchemaVersion(request: request, options: .init())
  }

  public func getRawSchemaVersion(
    request: GetVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getRawSchemaVersion(
    name: Swift.String,
  ) async throws -> GoogleApi.HttpBody {
    let request = GetVersionRequest().with {
      $0.name = name
    }
    return try await self.getRawSchemaVersion(request: request)
  }

  public func listVersions(request: ListVersionsRequest) async throws -> GoogleApi.HttpBody {
    try await self.listVersions(request: request, options: .init())
  }

  public func listVersions(
    request: ListVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listVersions(
    parent: Swift.String,
  ) async throws -> GoogleApi.HttpBody {
    let request = ListVersionsRequest().with {
      $0.parent = parent
    }
    return try await self.listVersions(request: request)
  }

  public func createVersion(request: CreateVersionRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse
  {
    try await self.createVersion(request: request, options: .init())
  }

  public func createVersion(
    request: CreateVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createVersion(
    parent: Swift.String,
    version: Swift.Int32?,
    id: Swift.Int32?,
    schemaType: Schema.SchemaType?,
    schema: Swift.String,
    references: [Schema.SchemaReference],
    normalize: Swift.Bool?,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse {
    let request = CreateVersionRequest().with {
      $0.parent = parent
      $0.version = version
      $0.id = id
      $0.schemaType = schemaType
      $0.schema = schema
      $0.references = references
      $0.normalize = normalize
    }
    return try await self.createVersion(request: request)
  }

  public func deleteVersion(request: DeleteVersionRequest) async throws -> GoogleApi.HttpBody {
    try await self.deleteVersion(request: request, options: .init())
  }

  public func deleteVersion(
    request: DeleteVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteVersion(
    name: Swift.String,
  ) async throws -> GoogleApi.HttpBody {
    let request = DeleteVersionRequest().with {
      $0.name = name
    }
    return try await self.deleteVersion(request: request)
  }

  public func listReferencedSchemas(request: ListReferencedSchemasRequest) async throws
    -> GoogleApi.HttpBody
  {
    try await self.listReferencedSchemas(request: request, options: .init())
  }

  public func listReferencedSchemas(
    request: ListReferencedSchemasRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApi.HttpBody {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listReferencedSchemas(
    parent: Swift.String,
  ) async throws -> GoogleApi.HttpBody {
    let request = ListReferencedSchemasRequest().with {
      $0.parent = parent
    }
    return try await self.listReferencedSchemas(request: request)
  }

  public func checkCompatibility(request: CheckCompatibilityRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse
  {
    try await self.checkCompatibility(request: request, options: .init())
  }

  public func checkCompatibility(
    request: CheckCompatibilityRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func checkCompatibility(
    name: Swift.String,
    schema: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse {
    let request = CheckCompatibilityRequest().with {
      $0.name = name
      $0.schema = schema
    }
    return try await self.checkCompatibility(request: request)
  }

  public func getSchemaConfig(request: GetSchemaConfigRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig
  {
    try await self.getSchemaConfig(request: request, options: .init())
  }

  public func getSchemaConfig(
    request: GetSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSchemaConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
    let request = GetSchemaConfigRequest().with {
      $0.name = name
    }
    return try await self.getSchemaConfig(request: request)
  }

  public func updateSchemaConfig(request: UpdateSchemaConfigRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig
  {
    try await self.updateSchemaConfig(request: request, options: .init())
  }

  public func updateSchemaConfig(
    request: UpdateSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSchemaConfig(
    name: Swift.String,
    compatibility: SchemaConfig.CompatibilityType?,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
    let request = UpdateSchemaConfigRequest().with {
      $0.name = name
      $0.compatibility = compatibility
    }
    return try await self.updateSchemaConfig(request: request)
  }

  public func deleteSchemaConfig(request: DeleteSchemaConfigRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig
  {
    try await self.deleteSchemaConfig(request: request, options: .init())
  }

  public func deleteSchemaConfig(
    request: DeleteSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSchemaConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
    let request = DeleteSchemaConfigRequest().with {
      $0.name = name
    }
    return try await self.deleteSchemaConfig(request: request)
  }

  public func getSchemaMode(request: GetSchemaModeRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode
  {
    try await self.getSchemaMode(request: request, options: .init())
  }

  public func getSchemaMode(
    request: GetSchemaModeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSchemaMode(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
    let request = GetSchemaModeRequest().with {
      $0.name = name
    }
    return try await self.getSchemaMode(request: request)
  }

  public func updateSchemaMode(request: UpdateSchemaModeRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode
  {
    try await self.updateSchemaMode(request: request, options: .init())
  }

  public func updateSchemaMode(
    request: UpdateSchemaModeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSchemaMode(
    name: Swift.String,
    mode: SchemaMode.ModeType,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
    let request = UpdateSchemaModeRequest().with {
      $0.name = name
      $0.mode = mode
    }
    return try await self.updateSchemaMode(request: request)
  }

  public func deleteSchemaMode(request: DeleteSchemaModeRequest) async throws
    -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode
  {
    try await self.deleteSchemaMode(request: request, options: .init())
  }

  public func deleteSchemaMode(
    request: DeleteSchemaModeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSchemaMode(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
    let request = DeleteSchemaModeRequest().with {
      $0.name = name
    }
    return try await self.deleteSchemaMode(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
