// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
import GoogleCloudLocation
import GoogleLongRunning
import GoogleWKT
import GoogleGax

extension Clients {
  protocol ManagedSchemaRegistryStub: Sendable {
    func getSchemaRegistry(
      request: GetSchemaRegistryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry

    func listSchemaRegistries(
      request: ListSchemaRegistriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse

    func createSchemaRegistry(
      request: CreateSchemaRegistryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry

    func deleteSchemaRegistry(
      request: DeleteSchemaRegistryRequest, options: GoogleGax.RequestOptions
    ) async throws

    func getContext(
      request: GetContextRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Context

    func listContexts(
      request: ListContextsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func getSchema(
      request: GetSchemaRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema

    func getRawSchema(
      request: GetSchemaRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func listSchemaVersions(
      request: ListSchemaVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func listSchemaTypes(
      request: ListSchemaTypesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func listSubjects(
      request: ListSubjectsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func listSubjectsBySchemaId(
      request: ListSubjectsBySchemaIdRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func deleteSubject(
      request: DeleteSubjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func lookupVersion(
      request: LookupVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion

    func getVersion(
      request: GetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion

    func getRawSchemaVersion(
      request: GetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func listVersions(
      request: ListVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func createVersion(
      request: CreateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse

    func deleteVersion(
      request: DeleteVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func listReferencedSchemas(
      request: ListReferencedSchemasRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func checkCompatibility(
      request: CheckCompatibilityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse

    func getSchemaConfig(
      request: GetSchemaConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    func updateSchemaConfig(
      request: UpdateSchemaConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    func deleteSchemaConfig(
      request: DeleteSchemaConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig

    func getSchemaMode(
      request: GetSchemaModeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    func updateSchemaMode(
      request: UpdateSchemaModeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    func deleteSchemaMode(
      request: DeleteSchemaModeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
