// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ManagedSchemaRegistryLogging: ManagedSchemaRegistryStub {
    let inner: any ManagedSchemaRegistryStub
    let logger: Logger

    public init(_ inner: any ManagedSchemaRegistryStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-managedkafka-schemaregistry-v1"
      logger[metadataKey: "gcp.client.service"] = "managedkafka"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ManagedSchemaRegistry"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getSchemaRegistry(
      request: GetSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSchemaRegistry",
        action: {
          (r: GetSchemaRegistryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry
          in
          return try await self.inner.getSchemaRegistry(request: r, options: o)
        })
    }

    public func listSchemaRegistries(
      request: ListSchemaRegistriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSchemaRegistries",
        action: {
          (r: ListSchemaRegistriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse
          in
          return try await self.inner.listSchemaRegistries(request: r, options: o)
        })
    }

    public func createSchemaRegistry(
      request: CreateSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSchemaRegistry",
        action: {
          (r: CreateSchemaRegistryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry
          in
          return try await self.inner.createSchemaRegistry(request: r, options: o)
        })
    }

    public func deleteSchemaRegistry(
      request: DeleteSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSchemaRegistry",
        action: {
          (r: DeleteSchemaRegistryRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSchemaRegistry(request: r, options: o)
        })
    }

    public func getContext(
      request: GetContextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Context {
      try await self._intercept(
        request: request,
        options: options,
        name: "getContext",
        action: {
          (r: GetContextRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.Context
          in
          return try await self.inner.getContext(request: r, options: o)
        })
    }

    public func listContexts(
      request: ListContextsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "listContexts",
        action: {
          (r: ListContextsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listContexts(request: r, options: o)
        })
    }

    public func getSchema(
      request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSchema",
        action: {
          (r: GetSchemaRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema
          in
          return try await self.inner.getSchema(request: r, options: o)
        })
    }

    public func getRawSchema(
      request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRawSchema",
        action: {
          (r: GetSchemaRequest, o: GoogleCloudGax.RequestOptions) async throws -> GoogleApi.HttpBody
          in
          return try await self.inner.getRawSchema(request: r, options: o)
        })
    }

    public func listSchemaVersions(
      request: ListSchemaVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSchemaVersions",
        action: {
          (r: ListSchemaVersionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listSchemaVersions(request: r, options: o)
        })
    }

    public func listSchemaTypes(
      request: ListSchemaTypesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSchemaTypes",
        action: {
          (r: ListSchemaTypesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listSchemaTypes(request: r, options: o)
        })
    }

    public func listSubjects(
      request: ListSubjectsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSubjects",
        action: {
          (r: ListSubjectsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listSubjects(request: r, options: o)
        })
    }

    public func listSubjectsBySchemaId(
      request: ListSubjectsBySchemaIdRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSubjectsBySchemaId",
        action: {
          (r: ListSubjectsBySchemaIdRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listSubjectsBySchemaId(request: r, options: o)
        })
    }

    public func deleteSubject(
      request: DeleteSubjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSubject",
        action: {
          (r: DeleteSubjectRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.deleteSubject(request: r, options: o)
        })
    }

    public func lookupVersion(
      request: LookupVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "lookupVersion",
        action: {
          (r: LookupVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion
          in
          return try await self.inner.lookupVersion(request: r, options: o)
        })
    }

    public func getVersion(
      request: GetVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "getVersion",
        action: {
          (r: GetVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion
          in
          return try await self.inner.getVersion(request: r, options: o)
        })
    }

    public func getRawSchemaVersion(
      request: GetVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRawSchemaVersion",
        action: {
          (r: GetVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.getRawSchemaVersion(request: r, options: o)
        })
    }

    public func listVersions(
      request: ListVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "listVersions",
        action: {
          (r: ListVersionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listVersions(request: r, options: o)
        })
    }

    public func createVersion(
      request: CreateVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "createVersion",
        action: {
          (r: CreateVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse
          in
          return try await self.inner.createVersion(request: r, options: o)
        })
    }

    public func deleteVersion(
      request: DeleteVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteVersion",
        action: {
          (r: DeleteVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.deleteVersion(request: r, options: o)
        })
    }

    public func listReferencedSchemas(
      request: ListReferencedSchemasRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "listReferencedSchemas",
        action: {
          (r: ListReferencedSchemasRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listReferencedSchemas(request: r, options: o)
        })
    }

    public func checkCompatibility(
      request: CheckCompatibilityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "checkCompatibility",
        action: {
          (r: CheckCompatibilityRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse
          in
          return try await self.inner.checkCompatibility(request: r, options: o)
        })
    }

    public func getSchemaConfig(
      request: GetSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSchemaConfig",
        action: {
          (r: GetSchemaConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig
          in
          return try await self.inner.getSchemaConfig(request: r, options: o)
        })
    }

    public func updateSchemaConfig(
      request: UpdateSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSchemaConfig",
        action: {
          (r: UpdateSchemaConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig
          in
          return try await self.inner.updateSchemaConfig(request: r, options: o)
        })
    }

    public func deleteSchemaConfig(
      request: DeleteSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSchemaConfig",
        action: {
          (r: DeleteSchemaConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig
          in
          return try await self.inner.deleteSchemaConfig(request: r, options: o)
        })
    }

    public func getSchemaMode(
      request: GetSchemaModeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSchemaMode",
        action: {
          (r: GetSchemaModeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode
          in
          return try await self.inner.getSchemaMode(request: r, options: o)
        })
    }

    public func updateSchemaMode(
      request: UpdateSchemaModeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSchemaMode",
        action: {
          (r: UpdateSchemaModeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode
          in
          return try await self.inner.updateSchemaMode(request: r, options: o)
        })
    }

    public func deleteSchemaMode(
      request: DeleteSchemaModeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSchemaMode",
        action: {
          (r: DeleteSchemaModeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode
          in
          return try await self.inner.deleteSchemaMode(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
