// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class ManagedSchemaRegistryRetry: ManagedSchemaRegistryStub {
    let inner: any ManagedSchemaRegistryStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any ManagedSchemaRegistryStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getSchemaRegistry(
      request: GetSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSchemaRegistryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry
          in
          return try await self.inner.getSchemaRegistry(request: r, options: o)
        })
    }

    public func listSchemaRegistries(
      request: ListSchemaRegistriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSchemaRegistriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.ListSchemaRegistriesResponse
          in
          return try await self.inner.listSchemaRegistries(request: r, options: o)
        })
    }

    public func createSchemaRegistry(
      request: CreateSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateSchemaRegistryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaRegistry
          in
          return try await self.inner.createSchemaRegistry(request: r, options: o)
        })
    }

    public func deleteSchemaRegistry(
      request: DeleteSchemaRegistryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteSchemaRegistryRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSchemaRegistry(request: r, options: o)
        })
    }

    public func getContext(
      request: GetContextRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Context {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetContextRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.Context
          in
          return try await self.inner.getContext(request: r, options: o)
        })
    }

    public func listContexts(
      request: ListContextsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListContextsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listContexts(request: r, options: o)
        })
    }

    public func getSchema(
      request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSchemaRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.Schema
          in
          return try await self.inner.getSchema(request: r, options: o)
        })
    }

    public func getRawSchema(
      request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSchemaRequest, o: GoogleCloudGax.RequestOptions) async throws -> GoogleApi.HttpBody
          in
          return try await self.inner.getRawSchema(request: r, options: o)
        })
    }

    public func listSchemaVersions(
      request: ListSchemaVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSchemaVersionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listSchemaVersions(request: r, options: o)
        })
    }

    public func listSchemaTypes(
      request: ListSchemaTypesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSchemaTypesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listSchemaTypes(request: r, options: o)
        })
    }

    public func listSubjects(
      request: ListSubjectsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSubjectsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listSubjects(request: r, options: o)
        })
    }

    public func listSubjectsBySchemaId(
      request: ListSubjectsBySchemaIdRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSubjectsBySchemaIdRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listSubjectsBySchemaId(request: r, options: o)
        })
    }

    public func deleteSubject(
      request: DeleteSubjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteSubjectRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.deleteSubject(request: r, options: o)
        })
    }

    public func lookupVersion(
      request: LookupVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: LookupVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion
          in
          return try await self.inner.lookupVersion(request: r, options: o)
        })
    }

    public func getVersion(
      request: GetVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaVersion
          in
          return try await self.inner.getVersion(request: r, options: o)
        })
    }

    public func getRawSchemaVersion(
      request: GetVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.getRawSchemaVersion(request: r, options: o)
        })
    }

    public func listVersions(
      request: ListVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListVersionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listVersions(request: r, options: o)
        })
    }

    public func createVersion(
      request: CreateVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.CreateVersionResponse
          in
          return try await self.inner.createVersion(request: r, options: o)
        })
    }

    public func deleteVersion(
      request: DeleteVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.deleteVersion(request: r, options: o)
        })
    }

    public func listReferencedSchemas(
      request: ListReferencedSchemasRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListReferencedSchemasRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.listReferencedSchemas(request: r, options: o)
        })
    }

    public func checkCompatibility(
      request: CheckCompatibilityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CheckCompatibilityRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.CheckCompatibilityResponse
          in
          return try await self.inner.checkCompatibility(request: r, options: o)
        })
    }

    public func getSchemaConfig(
      request: GetSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSchemaConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig
          in
          return try await self.inner.getSchemaConfig(request: r, options: o)
        })
    }

    public func updateSchemaConfig(
      request: UpdateSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: UpdateSchemaConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig
          in
          return try await self.inner.updateSchemaConfig(request: r, options: o)
        })
    }

    public func deleteSchemaConfig(
      request: DeleteSchemaConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteSchemaConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaConfig
          in
          return try await self.inner.deleteSchemaConfig(request: r, options: o)
        })
    }

    public func getSchemaMode(
      request: GetSchemaModeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSchemaModeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode
          in
          return try await self.inner.getSchemaMode(request: r, options: o)
        })
    }

    public func updateSchemaMode(
      request: UpdateSchemaModeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: UpdateSchemaModeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode
          in
          return try await self.inner.updateSchemaMode(request: r, options: o)
        })
    }

    public func deleteSchemaMode(
      request: DeleteSchemaModeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteSchemaModeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaSchemaRegistryV1.SchemaMode
          in
          return try await self.inner.deleteSchemaMode(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
