// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Version of a schema.
public struct SchemaVersion: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The subject of the version.
  public var subject: Swift.String = Swift.String()

  /// Required. The version ID
  public var versionId: Swift.Int32 = Swift.Int32()

  /// Required. The schema ID.
  public var schemaId: Swift.Int32 = Swift.Int32()

  /// Optional. The schema type of the schema.
  public var schemaType: Schema.SchemaType = Schema.SchemaType()

  /// Required. The schema payload.
  public var schemaPayload: Swift.String = Swift.String()

  /// Optional. The schema references used by the schema.
  public var references: [Schema.SchemaReference] = []

  /// Initialize a new instance of `SchemaVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SchemaVersion().with { $0.subject = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case subject = "subject"
    case versionId = "version"
    case schemaId = "id"
    case schemaType = "schemaType"
    case schemaPayload = "schema"
    case references = "references"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.subject = try container.decode(Swift.String.self, forKey: .subject)
    self.versionId = try container.decode(Swift.Int32.self, forKey: .versionId)
    self.schemaId = try container.decode(Swift.Int32.self, forKey: .schemaId)
    self.schemaType = try container.decode(Schema.SchemaType.self, forKey: .schemaType)
    self.schemaPayload = try container.decode(Swift.String.self, forKey: .schemaPayload)
    self.references = try container.decode([Schema.SchemaReference].self, forKey: .references)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.subject, forKey: .subject)
    try container.encode(self.versionId, forKey: .versionId)
    try container.encode(self.schemaId, forKey: .schemaId)
    try container.encode(self.schemaType, forKey: .schemaType)
    try container.encode(self.schemaPayload, forKey: .schemaPayload)
    try container.encode(self.references, forKey: .references)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.SchemaVersion"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
