// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// SchemaMode represents the mode of a schema registry or a specific subject.
/// Four modes are supported:
/// * NONE: deprecated. This was the default mode for a subject, but now the
/// default is unset (which means use the global schema registry setting)
/// * READONLY: The schema registry is in read-only mode.
/// * READWRITE: The schema registry is in read-write mode, which allows limited
/// write operations on the schema.
/// * IMPORT: The schema registry is in import mode, which allows more editing
/// operations on the schema for data importing purposes.
public struct SchemaMode: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The mode type of a schema registry (READWRITE by default) or of a
  /// subject (unset by default, which means use the global schema registry
  /// setting).
  public var mode: SchemaMode.ModeType = SchemaMode.ModeType()

  /// Initialize a new instance of `SchemaMode`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SchemaMode().with { $0.mode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Mode type of the schemas or subjects.
  public enum ModeType: Codable, Equatable, Sendable {
    /// The default / unset value.
    /// The subject mode is NONE/unset by default, which means use the global
    /// schema registry mode. This should not be used for setting the mode.
    case `none`
    /// READONLY mode.
    case readonly
    /// READWRITE mode.
    case readwrite
    /// IMPORT mode.
    case `import`
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .`none`
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .`none`: return 0
      case .readonly: return 1
      case .readwrite: return 2
      case .`import`: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .`none`: return "NONE"
      case .readonly: return "READONLY"
      case .readwrite: return "READWRITE"
      case .`import`: return "IMPORT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ModeType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "NONE": self = .`none`
      case "READONLY": self = .readonly
      case "READWRITE": self = .readwrite
      case "IMPORT": self = .`import`
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ModeType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .`none`
      case 1: self = .readonly
      case 2: self = .readwrite
      case 3: self = .`import`
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .`none`: return try container.encode(0)
      case .readonly: return try container.encode(1)
      case .readwrite: return try container.encode(2)
      case .`import`: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.SchemaMode"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
