// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// SchemaConfig represents configuration for a schema registry or a specific
/// subject.
public struct SchemaConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The compatibility type of the schema.
  /// The default value is BACKWARD.
  /// If unset in a SchemaSubject-level SchemaConfig, defaults to the global
  /// value. If unset in a SchemaRegistry-level SchemaConfig, reverts to the
  /// default value.
  public var compatibility: SchemaConfig.CompatibilityType? = nil

  /// Optional. If true, the schema will be normalized before being stored or
  /// looked up. The default is false. If unset in a SchemaSubject-level
  /// SchemaConfig, the global value will be used. If unset in a
  /// SchemaRegistry-level SchemaConfig, reverts to the default value.
  public var normalize: Swift.Bool? = nil

  /// Optional. The subject to which this subject is an alias of. Only applicable
  /// for subject config.
  public var alias: Swift.String = Swift.String()

  /// Initialize a new instance of `SchemaConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SchemaConfig().with { $0.compatibility = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Compatibility type of the schemas.
  public enum CompatibilityType: Codable, Equatable, Sendable {
    /// No compatibility check.
    case `none`
    /// Backwards compatible with the most recent version.
    case backward
    /// Backwards compatible with all previous versions.
    case backwardTransitive
    /// Forwards compatible with the most recent version.
    case forward
    /// Forwards compatible with all previous versions.
    case forwardTransitive
    /// Backwards and forwards compatible with the most recent version.
    case full
    /// Backwards and forwards compatible with all previous versions.
    case fullTransitive
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .`none`
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .`none`: return 0
      case .backward: return 1
      case .backwardTransitive: return 2
      case .forward: return 3
      case .forwardTransitive: return 4
      case .full: return 5
      case .fullTransitive: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .`none`: return "NONE"
      case .backward: return "BACKWARD"
      case .backwardTransitive: return "BACKWARD_TRANSITIVE"
      case .forward: return "FORWARD"
      case .forwardTransitive: return "FORWARD_TRANSITIVE"
      case .full: return "FULL"
      case .fullTransitive: return "FULL_TRANSITIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CompatibilityType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "NONE": self = .`none`
      case "BACKWARD": self = .backward
      case "BACKWARD_TRANSITIVE": self = .backwardTransitive
      case "FORWARD": self = .forward
      case "FORWARD_TRANSITIVE": self = .forwardTransitive
      case "FULL": self = .full
      case "FULL_TRANSITIVE": self = .fullTransitive
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CompatibilityType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .`none`
      case 1: self = .backward
      case 2: self = .backwardTransitive
      case 3: self = .forward
      case 4: self = .forwardTransitive
      case 5: self = .full
      case 6: self = .fullTransitive
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .`none`: return try container.encode(0)
      case .backward: return try container.encode(1)
      case .backwardTransitive: return try container.encode(2)
      case .forward: return try container.encode(3)
      case .forwardTransitive: return try container.encode(4)
      case .full: return try container.encode(5)
      case .fullTransitive: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.SchemaConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
