// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for updating schema config.
/// On a SchemaSubject-level SchemaConfig, an unset field will be removed from
/// the SchemaConfig.
public struct UpdateSchemaConfigRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name to update the config for. It can be either of
  /// following:
  ///   * projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/config: Update config at global level.
  ///   * projects/{project}/locations/{location}/schemaRegistries/{schema_registry}/config/{subject}: Update config for a specific subject.
  public var name: Swift.String = Swift.String()

  /// Required. The compatibility type of the schemas.
  /// Cannot be unset for a SchemaRegistry-level SchemaConfig.
  /// If unset on a SchemaSubject-level SchemaConfig, removes the compatibility
  /// field for the SchemaConfig.
  public var compatibility: SchemaConfig.CompatibilityType? = nil

  /// Optional. If true, the schema will be normalized before being stored or
  /// looked up. The default is false. Cannot be unset for a SchemaRegistry-level
  /// SchemaConfig. If unset on a SchemaSubject-level SchemaConfig, removes the
  /// normalize field for the SchemaConfig.
  public var normalize: Swift.Bool? = nil

  /// Initialize a new instance of `UpdateSchemaConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateSchemaConfigRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.managedkafka.schemaregistry.v1.UpdateSchemaConfigRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
